#include"Phanso.h"
int main()
{
	PhanSo a, b, c;
	cout << "Nhap phan so A: " << endl;
	cin >> a;
	cout << "Nhap phan so B: " << endl;
	cin >> b;
	cout << "\nPhan so A: " << a;
	cout << "Phan so B: " << b;
	cout << "\nToan tu gan =" << endl;
	c = a;
	cout << "C = A = ";
	cout << c;
	cout << "\nToan tu + - * /" << endl;
	c = a + b;
	cout << "A + B = " << c;
	c = a - b;
	cout << "A - B = " << c;
	c = a * b;
	cout << "A * B = " << c;
	c = a / b;
	cout << "A / B = " << c;
	cout << "\nToan tu +=  -=  *=  /=" << endl;
	c = a;
	a += b;
	cout << "A += B = " << a;
	a = c;
	a -= b;
	cout << "A -= B = " << a;
	a = c;
	a *= b;
	cout << "A *= B = " << a;
	a = c;
	a /= b;
	cout << "A /= B = " << a;
	a = c;
	cout << "\nToan tu ==  <  >  <=  >=  !=" << endl;
	if (a == b)cout << "A = B" << endl;
	if (a < b)cout << "A < B" << endl;
	if (a > b)cout << "A > B" << endl;
	if (a <= b)cout << "A <= B" << endl;
	if (a >= b)cout << "A >= B" << endl;
	if (a != b)cout << "A != B" << endl;
	cout << "\nToan tu tien to ++  --" << endl;
	++a;
	cout << "++A = " << a;
	a = c;
	--a;
	cout << "--A = " << a;
	a = c;
	cout << "\nToan tu hau to ++  --" << endl;
	b = a;
	c = a++;
	cout << "C = A++ " << endl;
	cout << "C = " << c;
	cout << "A = " << a;
	a = b;
	c = a--;
	cout << "\nC = A-- " << endl;
	cout << "C = " << c;
	cout << "A = " << a;
	return 0;
}